server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dongpeng2012/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 62.234.129.71
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'