server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 62.234.129.71
      port: 8599
      discovery:
        service-name: ${spring.application.name}
